### PR TITLE
Added Aeronautic Subsidy to cost calculator

### PR DESCRIPTION
**Pull request by JavaTryCatchMe**
Partially addresses #1
Sorry for whitespace change GH editor online bug.

### CODE REVIEW

**Review by blackeyefly — CHANGES_REQUESTED** [review]
I don't think this is taking MK into account? It needs to only apply the discount when MK is on.

**Comment by JavaTryCatchMe** [comment]
Had just noticed that when you posted it. I had broken each discount out separately (like village discount) initially but then in simplifying it lost the MK multiplier check I had.  Fixed.

**Comment by JavaTryCatchMe** [comment]
Fixed whitespace being added too.

**Comment by JavaTryCatchMe** [comment]
Going to close this and add the others as well with some cleanup.

**Pull request closed without merging**
